-- ============================================================
-- DEPRECATED — schema_schedules.sql
-- ============================================================
-- The compliance_schedules table is now included in schema.sql.
--
-- For fresh installs:   psql ... -f schema.sql
-- For existing installs upgrading to v2.6+, run only the new table:
--
--   PGPASSWORD=<pw> psql -h localhost -U configify_user -d configify_db << 'SQL'
--   CREATE TABLE IF NOT EXISTS compliance_schedules (
--       id               SERIAL PRIMARY KEY,
--       name             VARCHAR(255) NOT NULL,
--       description      TEXT,
--       golden_config_id INTEGER REFERENCES golden_configs(id) ON DELETE SET NULL,
--       enabled          BOOLEAN NOT NULL DEFAULT TRUE,
--       interval_hours   INTEGER NOT NULL DEFAULT 24 CHECK (interval_hours > 0),
--       last_run         TIMESTAMP WITH TIME ZONE,
--       next_run         TIMESTAMP WITH TIME ZONE,
--       run_count        INTEGER NOT NULL DEFAULT 0,
--       last_result      JSONB,
--       created_by       INTEGER REFERENCES users(id) ON DELETE SET NULL,
--       created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--       updated_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
--   );
--   CREATE INDEX IF NOT EXISTS idx_comp_sched_next_run
--       ON compliance_schedules(enabled, next_run) WHERE enabled = TRUE;
--   DO $$ BEGIN
--       IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_comp_schedules_updated_at') THEN
--           CREATE TRIGGER trg_comp_schedules_updated_at
--               BEFORE UPDATE ON compliance_schedules
--               FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--       END IF;
--   END $$;
--   SQL
-- ============================================================
\echo 'NOTE: schema_schedules.sql is superseded. Use schema.sql instead.'
