-- ============================================================
-- DEPRECATED — schema_compliance.sql
-- ============================================================
-- The compliance tables are now included in schema.sql.
--
-- For fresh installs:   psql ... -f schema.sql
-- For existing installs upgrading to v2.6+, run the
-- compliance + schedules tables directly:
--
--   PGPASSWORD=<pw> psql -h localhost -U configify_user -d configify_db \
--       -c "$(grep -A 9999 'COMPLIANCE CHECKING' schema.sql)"
--
-- Or apply schema.sql with IF NOT EXISTS guards — it is idempotent
-- and safe to re-run against an existing database.
-- ============================================================
\echo 'NOTE: schema_compliance.sql is superseded. Use schema.sql instead.'
