#!/usr/bin/env bash
# =============================================================
# configify — fresh-install bootstrap
# Tested on Ubuntu 24.04 LTS
#
# Usage:
#   sudo bash setup.sh
#
# What it does:
#   1. Installs system deps (Node 20, PostgreSQL 17, Nginx, PM2)
#   2. Creates DB + user
#   3. Applies schema.sql
#   4. Generates SESSION_SECRET + VAULT_SECRET
#   5. Writes .env
#   6. Installs npm packages
#   7. Starts the app with PM2
#   8. Configures Nginx (self-signed SSL)
# =============================================================
set -euo pipefail

# ── Variables — edit before running ──────────────────────────
APP_DIR="/var/www/configify"
APP_USER="${SUDO_USER:-$USER}"
DB_NAME="configify_db"
DB_USER="configify_user"
DB_PASS="$(openssl rand -base64 24)"
DOMAIN="configify.example.com"   # used for self-signed cert CN
PORT=3000

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}▶ $*${NC}"; }
warn()  { echo -e "${YELLOW}⚠ $*${NC}"; }

# Must run as root
[[ $EUID -ne 0 ]] && { echo "Run with sudo."; exit 1; }

# ── 1. System packages ────────────────────────────────────────
info "Updating system packages…"
apt-get update -qq
apt-get install -y -qq curl wget git ufw build-essential openssl

# Node.js 20
if ! command -v node &>/dev/null; then
    info "Installing Node.js 20…"
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
fi
info "Node $(node -v), npm $(npm -v)"

# PostgreSQL 17
if ! command -v psql &>/dev/null; then
    info "Installing PostgreSQL 17…"
    install -d /usr/share/postgresql-common/pgdg
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
        -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] \
        https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
        > /etc/apt/sources.list.d/pgdg.list
    apt-get update -qq
    apt-get install -y postgresql-17 postgresql-client-17
fi
systemctl enable --now postgresql

# Nginx
if ! command -v nginx &>/dev/null; then
    info "Installing Nginx…"
    apt-get install -y nginx
fi

# PM2
if ! command -v pm2 &>/dev/null; then
    info "Installing PM2…"
    npm install -g pm2 --quiet
fi

# ── 2. Firewall ───────────────────────────────────────────────
info "Configuring UFW…"
ufw allow OpenSSH  >/dev/null
ufw allow 80/tcp   >/dev/null
ufw allow 443/tcp  >/dev/null
ufw --force enable >/dev/null

# ── 3. Database ───────────────────────────────────────────────
info "Creating database and user…"

if [[ -z "${DB_PASS}" ]]; then
    DB_PASS="$(openssl rand -base64 24)"
fi

sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE USER "${DB_USER}" WITH PASSWORD '${DB_PASS}';
  END IF;
END \$\$;
CREATE DATABASE "${DB_NAME}"
  OWNER "${DB_USER}"
  ENCODING 'UTF8'
  TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME}" TO "${DB_USER}";
\c "${DB_NAME}"
GRANT ALL ON SCHEMA public TO "${DB_USER}";
SQL

# ── 4. App directory ──────────────────────────────────────────
info "Setting up application directory at ${APP_DIR}…"
mkdir -p "${APP_DIR}"
chown "${APP_USER}:${APP_USER}" "${APP_DIR}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ "${SCRIPT_DIR}" != "${APP_DIR}" ]]; then
    info "Copying application files…"
    cp -r "${SCRIPT_DIR}/." "${APP_DIR}/"
    chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}"
fi

# ── 5. Apply schema ───────────────────────────────────────────
info "Applying database schema…"
PGPASSWORD="${DB_PASS}" psql -h localhost -U "${DB_USER}" -d "${DB_NAME}" \
    -f "${APP_DIR}/schema.sql" -q

# ── 6. Generate secrets + .env ───────────────────────────────
info "Generating secrets…"
SESSION_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
VAULT_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"

cat > "${APP_DIR}/.env" <<ENV
# configify — generated by setup.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

PORT=${PORT}
NODE_ENV=production

DB_HOST=localhost
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASS}

SESSION_SECRET=${SESSION_SECRET}
VAULT_SECRET=${VAULT_SECRET}

APP_URL=https://${DOMAIN}
ENV
chmod 600 "${APP_DIR}/.env"
chown "${APP_USER}:${APP_USER}" "${APP_DIR}/.env"

# ── 7. npm install ────────────────────────────────────────────
info "Installing Node packages…"
cd "${APP_DIR}"
sudo -u "${APP_USER}" npm install --omit=dev --quiet

# ── 8. PM2 ───────────────────────────────────────────────────
info "Starting app with PM2…"
mkdir -p /var/log/configify
chown "${APP_USER}:${APP_USER}" /var/log/configify

sudo -u "${APP_USER}" pm2 start "${APP_DIR}/ecosystem.config.js" || \
sudo -u "${APP_USER}" pm2 restart configify-app

sudo -u "${APP_USER}" pm2 save
PM2_STARTUP_CMD=""
while IFS= read -r line; do
    PM2_STARTUP_CMD="${line}"
done < <(sudo -u "${APP_USER}" pm2 startup systemd -u "${APP_USER}" --hp "/home/${APP_USER}" 2>/dev/null | grep -E "^sudo ")

if [[ -n "${PM2_STARTUP_CMD}" ]]; then
    eval "${PM2_STARTUP_CMD}" 2>/dev/null || warn "PM2 startup script registration failed — run manually: pm2 startup"
else
    warn "Could not extract PM2 startup command — run 'pm2 startup' manually after install."
fi

# ── 9. Self-signed SSL cert ───────────────────────────────────
info "Generating self-signed SSL certificate…"
mkdir -p /etc/ssl/certs /etc/ssl/private
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout /etc/ssl/private/configify.key \
    -out    /etc/ssl/certs/configify.crt \
    -subj   "/CN=${DOMAIN}/O=configify/C=GB" 2>/dev/null
chmod 600 /etc/ssl/private/configify.key

# ── 10. Nginx ─────────────────────────────────────────────────
info "Configuring Nginx…"
cat > /etc/nginx/sites-available/configify <<NGINX
# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};
    return 301 https://\$server_name\$request_uri;
}

# HTTPS
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/ssl/certs/configify.crt;
    ssl_certificate_key /etc/ssl/private/configify.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    add_header X-Frame-Options   "SAMEORIGIN"  always;
    add_header X-Content-Type-Options "nosniff" always;

    access_log /var/log/nginx/configify_access.log;
    error_log  /var/log/nginx/configify_error.log;

    location / {
        proxy_pass         http://localhost:${PORT};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_connect_timeout 60s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/configify /etc/nginx/sites-enabled/configify
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl enable --now nginx
systemctl reload nginx

# ── 11. Database backup cron ──────────────────────────────────
info "Setting up daily database backup…"
mkdir -p /var/backups/postgresql
chown postgres:postgres /var/backups/postgresql

cat > /usr/local/bin/backup-configify-db.sh <<'BACKUP'
#!/bin/bash
BACKUP_DIR="/var/backups/postgresql"
DATE=$(date +%Y%m%d_%H%M%S)
DB_NAME="configify_db"
sudo -u postgres pg_dump $DB_NAME | gzip > $BACKUP_DIR/${DB_NAME}_$DATE.sql.gz
find $BACKUP_DIR -name "${DB_NAME}_*.sql.gz" -mtime +7 -delete
echo "Backup: ${DB_NAME}_$DATE.sql.gz"
BACKUP
chmod +x /usr/local/bin/backup-configify-db.sh

(crontab -l -u postgres 2>/dev/null || true; echo "0 2 * * * /usr/local/bin/backup-configify-db.sh") \
    | sort -u | crontab -u postgres -

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════"
echo -e "${GREEN}  configify installed successfully!${NC}"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  URL:            https://${DOMAIN}"
echo "  Admin login:    admin / ChangeMe2026!"
echo ""
echo "  ⚠️  Change the admin password immediately after login."
echo ""
echo "  DB password:    ${DB_PASS}"
echo "  Secrets saved:  ${APP_DIR}/.env"
echo ""
echo "  Useful commands:"
echo "    pm2 status"
echo "    pm2 logs configify-app"
echo "    pm2 restart configify-app"
echo "    nginx -t && systemctl reload nginx"
echo "════════════════════════════════════════════════════════"
